cacheDir: /cache/

gameDirectories:
  gcn:
    - /games/gcn

platforms:
  - name: Gamecube
    platform: gcn
    directories:
    - /games/gcn
  - name: Wii
    platform: wii
    directories:
    - /games/wii
