version: "3.9"
services:
  rex:
    build: .
    ports: 
    - "8080:8080"
    volumes:
    - ./testdir:/games
    - ./config.yaml:/config/config.yaml
  mongodb:
    image: mongo:latest
    command: --quiet
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
volumes:
  mongo_data: 
secrets:
  twitch-key:
    file: twitch-key.txt