version: "3.9"
services:
  rex:
    build: .
    ports: 
    - "8080:8080"
    environment:
    - PORT=8080
    - GIN_MODE=release
    volumes:
    - ./testdir:/games
    - ./config.yaml:/config/config.yaml
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
volumes:
  mongo_data: 