version: "3.9"
services:
  rex:
    build:
      dockerfile: backend.Dockerfile
    ports: 
    - "8080:8080"
    environment:
    - PORT=8080
    volumes:
    - ./testdir:/games
    - ./cache:/cache
    - ./config.yaml:/config/config.yaml
  rex-frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
    - "80:80"
    - "443:443"
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    ports:
    - 27017:27017
    volumes:
    - mongo_data:/data/db
volumes:
  mongo_data: 