cacheDir: /cache/
search:
  IGDB:
    twitch-client-id: <id>
    twitch-client-secret: <secret>
platforms:
  - name: Gamecube
    platform: gcn
    directories:
    - /games/gcn
  - name: Wii
    platform: wii
    directories:
    - /games/wii
  