// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/games": {
            "get": {
                "description": "Get a list of all of the games that Rex can find",
                "produces": [
                    "application/json"
                ],
                "summary": "Get All Games",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/games/byId": {
            "get": {
                "description": "Get a game by UUID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get game by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the game to search for",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/games/setGameById": {
            "post": {
                "description": "Get a game by UUID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get game by UUID",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/ping": {
            "get": {
                "description": "Pong!",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Ping!",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/platforms": {
            "get": {
                "description": "Returns a list of platforms with games in the library",
                "produces": [
                    "application/json"
                ],
                "summary": "Get platforms with games",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Rex",
	Description:      "Self Hostable Game Library",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
